### ISSUE TITLE
GMS 2?

### ISSUE THREAD

**Issue by JordanMagnuson** [RaniSputnik/dt#1]
Would love to see an official GMS 2 release of this awesome project!

**Comment by RaniSputnik** [comment]
Hey @JordanMagnuson I actually don't have GM2 but from my understanding it shouldn't be too difficult to do - as this project is entirely written in GML. Have you tried importing with GM2? What breaks?

**Comment by JordanMagnuson** [comment]
Thanks for the reply @RaniSputnik !

Everything imported into GMS2 without too much trouble. A decent number of compatibility scripts were generated, but I was able to get rid of / resolve most of those pretty easily (except for the view-related compatibility scripts pertaining to rmViewExample, as views work somewhat differently in GMS2 due to cameras).

Everything seems to be working, except for rmViewExample--which works, but not in HTML5. Though opening the project in GMS 1.4 reveals that rmViewExample does not work in HTML5 there either (it runs but the graphics glitch out completely)... have you ever gotten that example working in HMTL5?

**Comment by RaniSputnik** [comment]
@JordanMagnuson No, this didn't ever work.

If I remember correctly, I use a blend mode that wasn't supported in HTML5, (might be [this line here?](https://github.com/RaniSputnik/dt/blob/master/DestructableTerrain.gmx/scripts/__redraw_region.gml#L35)).

At the time I wrote this library, it was before [the graphics unification effort](https://www.yoyogames.com/blog/34/changes-to-the-gui-layer-and-the-new-application-su) that standardised the way that graphics work across all of GameMaker's platforms. 

A lot of surface and drawing functions didn't really work in HTML5, so it didn't seem feasible. It actually may be quite easy to get working - if the line that I linked to above is the problem, it should be too hard to find another way to clear and re-draw that works in HTML5.

That said, I don't have any time to sink into the project these days, so best of luck! I hope this context is usefull. Let me know if there's anything else I can help clarify 😄

**Comment by RaniSputnik** [comment]
Oh, how embarrassing! I've just read my own marketplace listing and apparently HTML5 was supported so I must've had it working at some stage 😖 I will have to remove this from the marketplace.

Apologies @JordanMagnuson I hope you weren't driven to purchase under false pretences. I thought I had cleaned up all my old extensions from the marketplace but obviously not.

**Comment by JordanMagnuson** [comment]
Thanks for taking the time to reply, Ryan--I really appreciate it! I'll see if I can get this working. :)

**Comment by JordanMagnuson** [comment]
(And I wouldn't remove the extension from the marketplace: it works great except for that one example in HTML5)
